tap "withgraphite/tap"

# CLI tools
brew "bat"
brew "eza"
brew "fd"
brew "gh"
brew "jq"
brew "mise"
brew "ripgrep"
brew "sk"
brew "uv"
brew "withgraphite/tap/graphite"

# Casks
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "claude-code"
cask "font-lilex"
cask "ghostty"
cask "google-chrome"
cask "monitorcontrol"
cask "notion-calendar"
cask "rectangle"
cask "zed"
